apiVersion: v1
kind: Service
metadata:
  name: evals-service
  namespace: cascade-system
  labels:
    app: evals-service
spec:
  selector:
    app: evals-service
  ports:
    - name: http
      port: 8041
      targetPort: http
